database:
  enabled: true

  # 数据库类型：sqlite / mysql
  type: sqlite

  # SQLite 配置（type = sqlite 时生效）
  sqlite:
    # 数据文件名，代码里再拼到插件 data 目录
    file: "bilibili_video.db"

  # MySQL 配置（type = mysql 时生效）
  mysql:
    host: "127.0.0.1"
    port: 3306
    database: "bilibili_video"
    username: "root"
    password: "password"
    # 额外 JDBC 参数
    params: "useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8"

  # 连接池（HikariCP）配置
  hikari:
    pool-name: "BilibiliVideoPool"

    maximum-pool-size: 10
    minimum-idle: 2

    connection-timeout: 30000      # 获取连接超时时间(ms)
    idle-timeout: 600000           # 空闲连接存活时间(ms)
    max-lifetime: 1800000          # 连接最大生命周期(ms)

    auto-commit: true
    read-only: false

  # 插件内部扩展配置
  options:
    table-prefix: "bv_"
    show-sql: false
    slow-sql-threshold-ms: 500     # 慢查询阈值（用于日志）

