name: Bug 报告
description: 提交一个 Bug 报告
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你提交 Bug 报告！请尽可能详细地填写以下信息，这将帮助我们更快地定位和修复问题。

        **提交前请确认：**
        - [ ] 我已搜索过现有 Issues，确认没有重复
        - [ ] 我使用的是最新版本的插件

  - type: input
    id: plugin-version
    attributes:
      label: 插件版本
      description: 使用 `/bv version` 或查看插件文件名获取
      placeholder: "例如: 2.0.5-59dca6b"
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: 服务端版本
      description: 使用 `/version` 命令获取
      placeholder: "例如: Paper 1.21.4"
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java 版本
      description: 启动日志中可以找到，或使用 `java -version`
      placeholder: "例如: Java 21"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 清晰简洁地描述遇到的问题
      placeholder: 描述你遇到的问题...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: 详细描述如何复现这个问题
      placeholder: |
        1. 执行命令 '...'
        2. 点击 '...'
        3. 出现错误 '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望行为
      description: 描述你期望发生什么
      placeholder: 我期望...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 相关日志
      description: |
        请提供相关的错误日志或控制台输出。
        **重要：** 请提供完整的报错堆栈，不要只截取部分。
      placeholder: |
        粘贴日志内容...

        提示：可以使用 https://paste.gg 或 https://mclo.gs 上传长日志
      render: text
    validations:
      required: true

  - type: textarea
    id: other-plugins
    attributes:
      label: 其他插件
      description: 列出服务器上安装的其他插件，特别是可能相关的插件（如反作弊、权限插件等）
      placeholder: |
        - PluginA
        - PluginB
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 任何其他可能有帮助的信息（截图、配置文件等）
    validations:
      required: false
